//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152405 on Stable branch
// Generated with ALiVE version 2.1.6.2410071
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_russiaspecial_ifa {
        displayName = "joschi_red_fraction";
        side = 0;
        flag = "\ca\data\flag_rus_co.paa";
        icon = "\ca\data\flag_rus_co.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_russiaspecial_ifa {
            name = "joschi_red_fraction";

            class Infantry {
                name = "Infantry";

                class o_russiaspecial_infantry_assault_squad_ifa {
                    name = "assault_squad";
                    side = 0;
                    faction = "O_russiaspecial_ifa";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_russiaspecial_joschi_red_ifa3_medic_ifa_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_russiaspecial_j0schi_red_ifa3_gunner_ifa_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_russiaspecial_joschi_red_ifa3_pt_a_ifa_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_russiaspecial_joschi_red_ifa3_pt_b_ifa_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_russiaspecial_joschi_red_ifa3_sniper_ifa_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_russiaspecial_joschi_red_ifa3_assault_ifa_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_russiaspecial_joschi_red_ifa3_assault_ifa_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class CUP_O_RUS_M_Soldier_Medic_VKPO_Summer;
    class CUP_O_RUS_M_Soldier_Medic_VKPO_Summer_OCimport_01 : CUP_O_RUS_M_Soldier_Medic_VKPO_Summer { scope = 0; class EventHandlers; };
    class CUP_O_RUS_M_Soldier_Medic_VKPO_Summer_OCimport_02 : CUP_O_RUS_M_Soldier_Medic_VKPO_Summer_OCimport_01 { class EventHandlers; };


    class O_russiaspecial_joschi_red_ifa3_medic_ifa_02 : CUP_O_RUS_M_Soldier_Medic_VKPO_Summer_OCimport_02 {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "joschi_red_ifa3_medic";
        side = 0;
        faction = "O_russiaspecial_ifa";

        identityTypes[] = {"Head_Asian","LanguageRUS_F"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_SVT_40","Sashka_Russian","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_SVT_40","Sashka_Russian","LIB_Binocular_SU"};

        magazines[] = {"LIB_10Rnd_762x54","LIB_10Rnd_762x54"};
        respawnMagazines[] = {"LIB_10Rnd_762x54","LIB_10Rnd_762x54"};

        backpack = "B_LIB_SOV_RA_Rucksack2_Gas_Kit_Green";

        ALiVE_orbatCreator_loadout[] = {{"LIB_SVT_40","","","",{"LIB_10Rnd_762x54",10},{},""},{},{"Sashka_Russian","","","",{},{},""},{"U_LIB_SOV_Razvedchik_am",{{"LIB_ACC_M1891_Bayo",1},{"PiR_bint",1},{"LIB_10Rnd_762x54",4,10}}},{"V_LIB_SOV_IShBrVestPPShDisc",{{"PiR_bint",9},{"LIB_10Rnd_762x54",8,10}}},{"B_LIB_SOV_RA_Rucksack2_Gas_Kit_Green",{{"PiR_bint",16},{"PiR_apteka",1},{"LIB_10Rnd_762x54",1,10}}},"H_LIB_SOV_RA_Helmet","G_Bandanna_blk",{"LIB_Binocular_SU","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_russiaspecial_j0schi_red_ifa3_gunner_ifa_01 : O_russiaspecial_joschi_red_ifa3_medic_ifa_02 {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "j0schi_red_ifa3_gunner";
        side = 0;
        faction = "O_russiaspecial_ifa";

        identityTypes[] = {"Head_Asian","LanguageRUS_F"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_DT_OPTIC","WBK_survival_weapon_3","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_DT_OPTIC","WBK_survival_weapon_3","LIB_Binocular_SU"};

        magazines[] = {"LIB_63Rnd_762x54","LIB_63Rnd_762x54"};
        respawnMagazines[] = {"LIB_63Rnd_762x54","LIB_63Rnd_762x54"};

        backpack = "B_LIB_SOV_RA_Rucksack2_Gas_Kit_Green";

        ALiVE_orbatCreator_loadout[] = {{"LIB_DT_OPTIC","","","",{"LIB_63Rnd_762x54",63},{},""},{},{"WBK_survival_weapon_3","","","",{},{},""},{"U_LIB_SOV_Razvedchik_am",{{"LIB_ACC_M1891_Bayo",1},{"PiR_bint",3}}},{"V_LIB_SOV_IShBrVestPPShDisc",{{"PiR_bint",6},{"LIB_63Rnd_762x54",2,63}}},{"B_LIB_SOV_RA_Rucksack2_Gas_Kit_Green",{{"PiR_bint",11},{"PiR_apteka",1},{"LIB_63Rnd_762x54",2,63}}},"H_LIB_SOV_RA_Helmet","G_Bandanna_blk",{"LIB_Binocular_SU","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_russiaspecial_joschi_red_ifa3_assault_ifa_01 : O_russiaspecial_joschi_red_ifa3_medic_ifa_02 {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "joschi_red_ifa3_assault";
        side = 0;
        faction = "O_russiaspecial_ifa";

        identityTypes[] = {"Head_Asian","LanguageRUS_F"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_PPSh41_m","Axe","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_PPSh41_m","Axe","LIB_Binocular_SU"};

        magazines[] = {"LIB_35Rnd_762x25","LIB_35Rnd_762x25"};
        respawnMagazines[] = {"LIB_35Rnd_762x25","LIB_35Rnd_762x25"};

        backpack = "B_LIB_SOV_RA_Rucksack2_Gas_Kit_Green";

        ALiVE_orbatCreator_loadout[] = {{"LIB_PPSh41_m","","","",{"LIB_35Rnd_762x25",35},{},""},{},{"Axe","","","",{},{},""},{"U_LIB_SOV_Razvedchik_am",{{"LIB_ACC_M1891_Bayo",1},{"PiR_bint",3}}},{"V_LIB_SOV_IShBrVestPPShDisc",{{"PiR_bint",8},{"LIB_35Rnd_762x25",2,35},{"LIB_71Rnd_762x25_t",2,71}}},{"B_LIB_SOV_RA_Rucksack2_Gas_Kit_Green",{{"PiR_bint",16},{"PiR_apteka",1}}},"H_LIB_SOV_RA_Helmet","G_Bandanna_blk",{"LIB_Binocular_SU","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_russiaspecial_joschi_red_ifa3_pt_a_ifa_01 : O_russiaspecial_joschi_red_ifa3_medic_ifa_02 {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "joschi_red_ifa3_pt_a";
        side = 0;
        faction = "O_russiaspecial_ifa";

        identityTypes[] = {"Head_Asian","LanguageRUS_F"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_PTRD","WBK_survival_weapon_3","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_PTRD","WBK_survival_weapon_3","LIB_Binocular_SU"};

        magazines[] = {"LIB_1Rnd_145x114","LIB_1Rnd_145x114"};
        respawnMagazines[] = {"LIB_1Rnd_145x114","LIB_1Rnd_145x114"};

        backpack = "B_LIB_SOV_RA_Rucksack2_Gas_Kit_Green";

        ALiVE_orbatCreator_loadout[] = {{"LIB_PTRD","","","",{"LIB_1Rnd_145x114",1},{},""},{},{"WBK_survival_weapon_3","","","",{},{},""},{"U_LIB_SOV_Razvedchik_am",{{"LIB_ACC_M1891_Bayo",1},{"PiR_bint",3}}},{"V_LIB_SOV_IShBrVestPPShDisc",{{"PiR_bint",6},{"LIB_1Rnd_145x114",11,1}}},{"B_LIB_SOV_RA_Rucksack2_Gas_Kit_Green",{{"PiR_bint",11},{"PiR_apteka",1},{"LIB_1Rnd_145x114",8,1}}},"H_LIB_SOV_RA_Helmet","G_Bandanna_blk",{"LIB_Binocular_SU","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_russiaspecial_joschi_red_ifa3_sniper_ifa_01 : O_russiaspecial_joschi_red_ifa3_medic_ifa_02 {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "joschi_red_ifa3_sniper";
        side = 0;
        faction = "O_russiaspecial_ifa";

        identityTypes[] = {"Head_Asian","LanguageRUS_F"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_M9130PU","WBK_survival_weapon_3","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_M9130PU","WBK_survival_weapon_3","LIB_Binocular_SU"};

        magazines[] = {"LIB_5Rnd_762x54","LIB_5Rnd_762x54"};
        respawnMagazines[] = {"LIB_5Rnd_762x54","LIB_5Rnd_762x54"};

        backpack = "B_LIB_SOV_RA_Rucksack2_Gas_Kit_Green";

        ALiVE_orbatCreator_loadout[] = {{"LIB_M9130PU","","","",{"LIB_5Rnd_762x54",5},{},""},{},{"WBK_survival_weapon_3","","","",{},{},""},{"U_LIB_SOV_Razvedchik_am",{{"LIB_ACC_M1891_Bayo",1},{"PiR_bint",2},{"LIB_5Rnd_762x54",3,5}}},{"V_LIB_SOV_IShBrVestPPShDisc",{{"PiR_bint",10},{"LIB_5Rnd_762x54",11,5}}},{"B_LIB_SOV_RA_Rucksack2_Gas_Kit_Green",{{"PiR_bint",16},{"PiR_apteka",1},{"LIB_5Rnd_762x54",2,5}}},"H_LIB_SOV_RA_Helmet","G_Bandanna_blk",{"LIB_Binocular_SU","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_russiaspecial_joschi_red_ifa3_pt_b_ifa_01 : O_russiaspecial_joschi_red_ifa3_pt_a_ifa_01 {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "joschi_red_ifa3_pt_b";
        side = 0;
        faction = "O_russiaspecial_ifa";

        identityTypes[] = {"Head_Asian","LanguageRUS_F"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_PPSh41_m","LIB_M1A1_Bazooka","WBK_survival_weapon_3","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_PPSh41_m","LIB_M1A1_Bazooka","WBK_survival_weapon_3","LIB_Binocular_SU"};

        magazines[] = {"LIB_35Rnd_762x25","LIB_1Rnd_60mm_M6","LIB_35Rnd_762x25"};
        respawnMagazines[] = {"LIB_35Rnd_762x25","LIB_1Rnd_60mm_M6","LIB_35Rnd_762x25"};

        backpack = "B_LIB_US_M36_Rocketbag_Empty";

        ALiVE_orbatCreator_loadout[] = {{"LIB_PPSh41_m","","","",{"LIB_35Rnd_762x25",35},{},""},{"LIB_M1A1_Bazooka","","","",{"LIB_1Rnd_60mm_M6",1},{},""},{"WBK_survival_weapon_3","","","",{},{},""},{"U_LIB_SOV_Razvedchik_am",{{"LIB_ACC_M1891_Bayo",1},{"PiR_bint",3}}},{"V_LIB_SOV_IShBrVestPPShDisc",{{"PiR_bint",7},{"LIB_35Rnd_762x25",4,35},{"LIB_71Rnd_762x25_t",2,71}}},{"B_LIB_US_M36_Rocketbag_Empty",{{"LIB_1Rnd_60mm_M6",2,1}}},"H_LIB_SOV_RA_Helmet","G_Bandanna_blk",{"LIB_Binocular_SU","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};