//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152405 on Stable branch
// Generated with ALiVE version 2.1.6.2410071
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class joschi_ifa3_rus_fraction {
        displayName = "J0SCHI IFA3 SSSR ";
        side = 0;
        flag = "\a3\UI_F_Enoch\Data\CfgMarkers\Russia_CA.paa";
        icon = "\a3\UI_F_Enoch\Data\CfgMarkers\Russia_CA.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class joschi_ifa3_rus_fraction {
            name = "J0SCHI IFA3 SSSR ";

            class Infantry {
                name = "Infantry";

                class joschi_ifa3_rus_assault_squad {
                    name = "joschi_ifa3_rus_assault_squad";
                    side = 0;
                    faction = "joschi_ifa3_rus_fraction";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "joschi_ifa3_rus_medic";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "joschi_ifa3_rus_sniper";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "joschi_ifa3_rus_gunner";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "joschi_ifa3_rus_pt_a";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "joschi_ifa3_rus_pt_b";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "joschi_ifa3_rus_assault";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "joschi_ifa3_rus_assault";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LIB_SOV_medic;
    class LIB_SOV_medic_OCimport_01 : LIB_SOV_medic { scope = 0; class EventHandlers; };
    class LIB_SOV_medic_OCimport_02 : LIB_SOV_medic_OCimport_01 { class EventHandlers; };


    class joschi_ifa3_rus_medic : LIB_SOV_medic_OCimport_02 {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "joschi_ifa3_rus_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_SU","LIB_Glasses"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_SVT_40","LIB_TT33","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_SVT_40","LIB_TT33","LIB_Binocular_SU"};

        magazines[] = {"LIB_10Rnd_762x54","LIB_8Rnd_762x25","LIB_10Rnd_762x54","LIB_8Rnd_762x25"};
        respawnMagazines[] = {"LIB_10Rnd_762x54","LIB_8Rnd_762x25","LIB_10Rnd_762x54","LIB_8Rnd_762x25"};

        backpack = "B_LIB_SOV_RA_MedicalBag";
    };

    class joschi_ifa3_rus_assault : joschi_ifa3_rus_medic {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assault";
        side = 0;
        faction = "joschi_ifa3_rus_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_SU","LIB_Glasses"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_PPSh41_m","LIB_TT33","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_PPSh41_m","LIB_TT33","LIB_Binocular_SU"};

        magazines[] = {"LIB_35Rnd_762x25","LIB_8Rnd_762x25","LIB_35Rnd_762x25","LIB_8Rnd_762x25"};
        respawnMagazines[] = {"LIB_35Rnd_762x25","LIB_8Rnd_762x25","LIB_35Rnd_762x25","LIB_8Rnd_762x25"};

        backpack = "B_LIB_SOV_RA_MedicalBag";
    };

    class joschi_ifa3_rus_sniper : joschi_ifa3_rus_medic {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "joschi_ifa3_rus_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_SU","LIB_Glasses"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_M9130PU","LIB_TT33","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_M9130PU","LIB_TT33","LIB_Binocular_SU"};

        magazines[] = {"LIB_5Rnd_762x54","LIB_8Rnd_762x25","LIB_5Rnd_762x54","LIB_8Rnd_762x25"};
        respawnMagazines[] = {"LIB_5Rnd_762x54","LIB_8Rnd_762x25","LIB_5Rnd_762x54","LIB_8Rnd_762x25"};

        backpack = "B_LIB_SOV_RA_MedicalBag";
    };

    class joschi_ifa3_rus_gunner : joschi_ifa3_rus_medic {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "Gunner";
        side = 0;
        faction = "joschi_ifa3_rus_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_SU","LIB_Glasses"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_DT_OPTIC","LIB_TT33","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_DT_OPTIC","LIB_TT33","LIB_Binocular_SU"};

        magazines[] = {"LIB_63Rnd_762x54","LIB_8Rnd_762x25","LIB_63Rnd_762x54","LIB_8Rnd_762x25"};
        respawnMagazines[] = {"LIB_63Rnd_762x54","LIB_8Rnd_762x25","LIB_63Rnd_762x54","LIB_8Rnd_762x25"};

        backpack = "B_LIB_SOV_RA_MedicalBag";
    };

    class joschi_ifa3_rus_pt_a : joschi_ifa3_rus_medic {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "PT Assault a";
        side = 0;
        faction = "joschi_ifa3_rus_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_SU","LIB_Glasses"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_PTRD","LIB_TT33","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_PTRD","LIB_TT33","LIB_Binocular_SU"};

        magazines[] = {"LIB_1Rnd_145x114","LIB_8Rnd_762x25","LIB_1Rnd_145x114","LIB_8Rnd_762x25"};
        respawnMagazines[] = {"LIB_1Rnd_145x114","LIB_8Rnd_762x25","LIB_1Rnd_145x114","LIB_8Rnd_762x25"};

        backpack = "B_LIB_SOV_RA_MedicalBag";
    };

    class joschi_ifa3_rus_pt_b : joschi_ifa3_rus_medic {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "PT Assault b";
        side = 0;
        faction = "joschi_ifa3_rus_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_SU","LIB_Glasses"};

        uniformClass = "U_LIB_SOV_Razvedchik_am";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShDisc","H_LIB_SOV_RA_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"LIB_PPSh41_m","LIB_M1A1_Bazooka","LIB_TT33","LIB_Binocular_SU"};
        respawnWeapons[] = {"LIB_PPSh41_m","LIB_M1A1_Bazooka","LIB_TT33","LIB_Binocular_SU"};

        magazines[] = {"LIB_35Rnd_762x25","LIB_1Rnd_60mm_M6","LIB_8Rnd_762x25","LIB_35Rnd_762x25","LIB_8Rnd_762x25"};
        respawnMagazines[] = {"LIB_35Rnd_762x25","LIB_1Rnd_60mm_M6","LIB_8Rnd_762x25","LIB_35Rnd_762x25","LIB_8Rnd_762x25"};

        backpack = "B_LIB_SOV_RA_MedicalBag";
    };

};