//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152405 on Stable branch
// Generated with ALiVE version 2.1.6.2410071
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class joschi_ifa3_ger_fraction {
        displayName = "Р™РћРЁР IFA3 РђСЂРјРёСЏ РіРµСЂРјР°РЅРёРё";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\Germany_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\Germany_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        class joschi_ifa3_ger_fraction {
            name = "Р™РћРЁР IFA3 РђСЂРјРёСЏ РіРµСЂРјР°РЅРёРё";

            class Infantry {
                name = "Infantry";

                class joschi_ifa3_ger_assault_squad {
                    name = "joschi_ifa3_ger_assault_squad";
                    side = 1;
                    faction = "joschi_ifa3_ger_fraction";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "joschi_ifa3_ger_medic";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "joschi_ifa3_ger_sniper";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "joschi_ifa3_ger_gunner";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "joschi_ifa3_ger_pt";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "joschi_ifa3_ger_assault";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "joschi_ifa3_ger_assault";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "joschi_ifa3_ger_assault";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LIB_GER_medic;
    class LIB_GER_medic_OCimport_01 : LIB_GER_medic { scope = 0; class EventHandlers; };
    class LIB_GER_medic_OCimport_02 : LIB_GER_medic_OCimport_01 { class EventHandlers; };


    class joschi_ifa3_ger_medic : LIB_GER_medic_OCimport_02 {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "РњРµРґРёРє";
        side = 1;
        faction = "joschi_ifa3_ger_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","LIB_Glasses"};

        uniformClass = "U_LIB_GER_MG_schutze";

        linkedItems[] = {"V_LIB_WP_OfficerVest","H_LIB_GER_Helmet_Glasses","ItemMap","LIB_GER_ItemCompass_deg","LIB_GER_ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_WP_OfficerVest","H_LIB_GER_Helmet_Glasses","ItemMap","LIB_GER_ItemCompass_deg","LIB_GER_ItemWatch"};

        weapons[] = {"LIB_MP44","LIB_P38","LIB_Binocular_GER"};
        respawnWeapons[] = {"LIB_MP44","LIB_P38","LIB_Binocular_GER"};

        magazines[] = {"LIB_30Rnd_792x33","LIB_8Rnd_9x19","LIB_30Rnd_792x33","LIB_8Rnd_9x19"};
        respawnMagazines[] = {"LIB_30Rnd_792x33","LIB_8Rnd_9x19","LIB_30Rnd_792x33","LIB_8Rnd_9x19"};

        backpack = "B_LIB_GER_MedicBackpack";
    };

    class joschi_ifa3_ger_assault : joschi_ifa3_ger_medic {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "РЁС‚СѓСЂРјРѕРІРёРє";
        side = 1;
        faction = "joschi_ifa3_ger_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","LIB_Glasses"};

        uniformClass = "U_LIB_GER_MG_schutze";

        linkedItems[] = {"V_LIB_WP_OfficerVest","H_LIB_GER_Helmet_Glasses","ItemMap","LIB_GER_ItemCompass_deg","LIB_GER_ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_WP_OfficerVest","H_LIB_GER_Helmet_Glasses","ItemMap","LIB_GER_ItemCompass_deg","LIB_GER_ItemWatch"};

        weapons[] = {"LIB_MP40","LIB_P38","LIB_Binocular_GER"};
        respawnWeapons[] = {"LIB_MP40","LIB_P38","LIB_Binocular_GER"};

        magazines[] = {"LIB_32Rnd_9x19","LIB_8Rnd_9x19","LIB_32Rnd_9x19","LIB_8Rnd_9x19"};
        respawnMagazines[] = {"LIB_32Rnd_9x19","LIB_8Rnd_9x19","LIB_32Rnd_9x19","LIB_8Rnd_9x19"};

        backpack = "B_LIB_GER_MedicBackpack";
    };

    class joschi_ifa3_ger_sniper : joschi_ifa3_ger_medic {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "РЎРЅР°Р№РїРµСЂ";
        side = 1;
        faction = "joschi_ifa3_ger_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","LIB_Glasses"};

        uniformClass = "U_LIB_GER_MG_schutze";

        linkedItems[] = {"V_LIB_WP_OfficerVest","H_LIB_GER_Helmet_Glasses","ItemMap","LIB_GER_ItemCompass_deg","LIB_GER_ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_WP_OfficerVest","H_LIB_GER_Helmet_Glasses","ItemMap","LIB_GER_ItemCompass_deg","LIB_GER_ItemWatch"};

        weapons[] = {"LIB_K98ZF39","LIB_TT33","LIB_Binocular_GER"};
        respawnWeapons[] = {"LIB_K98ZF39","LIB_TT33","LIB_Binocular_GER"};

        magazines[] = {"LIB_5Rnd_792x57","LIB_8Rnd_762x25","LIB_5Rnd_792x57","LIB_8Rnd_762x25"};
        respawnMagazines[] = {"LIB_5Rnd_792x57","LIB_8Rnd_762x25","LIB_5Rnd_792x57","LIB_8Rnd_762x25"};

        backpack = "B_LIB_GER_MedicBackpack";
    };

    class joschi_ifa3_ger_gunner : joschi_ifa3_ger_medic {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "РџСѓР»РµРјРµС‚С‡РёРє";
        side = 1;
        faction = "joschi_ifa3_ger_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","LIB_Glasses"};

        uniformClass = "U_LIB_GER_MG_schutze";

        linkedItems[] = {"V_LIB_WP_OfficerVest","H_LIB_GER_Helmet_Glasses","ItemMap","LIB_GER_ItemCompass_deg","LIB_GER_ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_WP_OfficerVest","H_LIB_GER_Helmet_Glasses","ItemMap","LIB_GER_ItemCompass_deg","LIB_GER_ItemWatch"};

        weapons[] = {"LIB_MG42","LIB_P38","LIB_Binocular_GER"};
        respawnWeapons[] = {"LIB_MG42","LIB_P38","LIB_Binocular_GER"};

        magazines[] = {"LIB_50Rnd_792x57","LIB_8Rnd_9x19","LIB_50Rnd_792x57","LIB_8Rnd_9x19"};
        respawnMagazines[] = {"LIB_50Rnd_792x57","LIB_8Rnd_9x19","LIB_50Rnd_792x57","LIB_8Rnd_9x19"};

        backpack = "B_LIB_GER_MedicBackpack";
    };

    class joschi_ifa3_ger_pt : joschi_ifa3_ger_medic {
        author = "j0sch";
        scope = 2;
        scopeCurator = 2;
        displayName = "РџРў РЎС‚СЂРµР»РѕРє";
        side = 1;
        faction = "joschi_ifa3_ger_fraction";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","LIB_Glasses"};

        uniformClass = "U_LIB_GER_MG_schutze";

        linkedItems[] = {"V_LIB_WP_OfficerVest","H_LIB_GER_Helmet_Glasses","ItemMap","LIB_GER_ItemCompass_deg","LIB_GER_ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_WP_OfficerVest","H_LIB_GER_Helmet_Glasses","ItemMap","LIB_GER_ItemCompass_deg","LIB_GER_ItemWatch"};

        weapons[] = {"LIB_MP40","LIB_RPzB","LIB_P38","LIB_Binocular_GER"};
        respawnWeapons[] = {"LIB_MP40","LIB_RPzB","LIB_P38","LIB_Binocular_GER"};

        magazines[] = {"LIB_32Rnd_9x19","LIB_1Rnd_RPzB","LIB_8Rnd_9x19","LIB_32Rnd_9x19","LIB_8Rnd_9x19"};
        respawnMagazines[] = {"LIB_32Rnd_9x19","LIB_1Rnd_RPzB","LIB_8Rnd_9x19","LIB_32Rnd_9x19","LIB_8Rnd_9x19"};

        backpack = "B_LIB_GER_MedicBackpack";
    };

};